trigger:
  - staging

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: bin/build
        displayName: Build IZR Files
      - task: Docker@2
        displayName: Push Docker Image
        inputs:
          command: buildAndPush
          containerRegistry: SteeltoeContainerRegistry
          repository: initializr-izrs
          tags: |
            $(Build.BuildId)
      - task: KubernetesManifest@0
        displayName: Deploy to Staging
        inputs:
          action: deploy
          kubernetesServiceConnection: SteeltoeStagingAKS
          namespace: initializr
          manifests: |
            deploy/kubernetes/staging.yaml
          containers: |
            steeltoe.azurecr.io/initializr-izrs:$(Build.BuildId)
