trigger:
  - master

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - bash: bin/build
        displayName: Build IZR Files
      - task: Docker@2
        displayName: Push Docker Image
        inputs:
          command: buildAndPush
          containerRegistry: SteeltoeContainerRegistry
          repository: initializr-izrs
          tags: |
            $(Build.BuildId)
            latest
        condition:
          and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')))
      - task: KubernetesManifest@0
        displayName: Deploy to Production
        inputs:
          kubernetesServiceConnection: SteeltoeProductionAKS
          namespace: initializr
          action: deploy
          manifests: deploy/kubernetes/*.yaml
          containers: steeltoe.azurecr.io/initializr-izrs:$(Build.BuildId)
        condition:
          and(succeeded(), not(eq(variables['build.reason'], 'PullRequest')))
      - task: Kubernetes@1
        displayName: Restart InitializrApi
        inputs:
          connectionType: Kubernetes Service Connection
          kubernetesServiceEndpoint: SteeltoeProductionAKS
          namespace: initializr
          command: rollout
          arguments: restart deployment/initializr-api
